### PR TITLE
Deploy to cloud

### PR DESCRIPTION
**Pull request by greshilov**
This change is [Reviewable](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1)

### CODE REVIEW

**Review by nikicat — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1)* status: all files reviewed, 4 unresolved discussions (waiting on @aa-tolmachev and @greshilov)

___
*[chart/templates/deployment.yaml, line 43 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoEOoLDC9EiYr1Hlmo:-MKoEOoLDC9EiYr1Hlmp:b-srbx8f) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/deployment.yaml#L43)):*
> ```YAML
>             - python
>             - manage.py
>             - warmup
> ```

он только один раз будет скачивать модель или при каждом старте?
___
*[chart/templates/deployment.yaml, line 50 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoDnOs0w0dzkAtnt0r:-MKoDnOs0w0dzkAtnt0s:b-b6w0ql) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/deployment.yaml#L50)):*
> ```YAML
>         - name: app
>           image: {{ template "image" . }}
>           imagePullPolicy: {{ .Values.image.pullPolicy }}
> ```

лучше дефолтную оставлять, даже менять смысла нет (т.к. мы sha суммы используем)
___
*[chart/templates/service.yaml, line 19 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoEL_61AxlI-ezQhVJ:-MKoEL_61AxlI-ezQhVK:bz4emm0) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/service.yaml#L19)):*
> ```YAML
> spec:
>   type: {{ $service.type }}
>   {{- if eq $service.type "ExternalName" }}
> ```

можно убрать
___
*[meta/urls.py, line 5 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoE7RPDdeYZiwnhmX8:-MKoE7RPDdeYZiwnhmX9:b9p8vye) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/meta/urls.py#L5)):*
> ```Python
> 
> 
> prefix = 'wot-qa' if settings.IN_CLOUD else ''
> ```

лучше сделать явную настройку PREFIX, чем флаг IN_CLOUD

**Review by greshilov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1)* status: 13 of 18 files reviewed, 4 unresolved discussions (waiting on @aa-tolmachev and @nikicat)

___
*[chart/templates/deployment.yaml, line 43 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoEOoLDC9EiYr1Hlmo:-MKoHFMgCvqNwRfQWvQt:b-1rbsay) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/deployment.yaml#L43)):*
<details><summary><i>Previously, nikicat (Nikolay Bryskin) wrote…</i></summary><blockquote>

он только один раз будет скачивать модель или при каждом старте?
</blockquote></details>

При каждом новом деплое. Он скачивает ее в `volume`,  который потом передается приложению.
___
*[chart/templates/deployment.yaml, line 50 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoDnOs0w0dzkAtnt0r:-MKoHfGt5yx7IyiAA2Uw:b-896fix) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/deployment.yaml#L50)):*
<details><summary><i>Previously, nikicat (Nikolay Bryskin) wrote…</i></summary><blockquote>

лучше дефолтную оставлять, даже менять смысла нет (т.к. мы sha суммы используем)
</blockquote></details>

Done.
___
*[chart/templates/service.yaml, line 19 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoEL_61AxlI-ezQhVJ:-MKoHkQA7YLguEUHI_7V:b-896fix) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/service.yaml#L19)):*
<details><summary><i>Previously, nikicat (Nikolay Bryskin) wrote…</i></summary><blockquote>

можно убрать
</blockquote></details>

Done.
___
*[meta/urls.py, line 5 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoE7RPDdeYZiwnhmX8:-MKoIo4lBerryMZun4ey:b-896fix) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/meta/urls.py#L5)):*
<details><summary><i>Previously, nikicat (Nikolay Bryskin) wrote…</i></summary><blockquote>

лучше сделать явную настройку PREFIX, чем флаг IN_CLOUD
</blockquote></details>

Done.

**Review by nikicat — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1)* status: all files reviewed, 1 unresolved discussion (waiting on @aa-tolmachev and @greshilov)

___
*[chart/templates/deployment.yaml, line 43 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoEOoLDC9EiYr1Hlmo:-MKoJR-AEXdboNkTZuew:b-5efzbe) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/deployment.yaml#L43)):*
<details><summary><i>Previously, greshilov (Slava) wrote…</i></summary><blockquote>

При каждом новом деплое. Он скачивает ее в `volume`,  который потом передается приложению.
</blockquote></details>

Между крешами контейнера файлы будут сохраняться, но если будет переезд на другую ноду - потеряются. А там код проверяет, что если модель уже есть, то второй раз не надо качать?

**Review by greshilov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1)* status: all files reviewed, 1 unresolved discussion (waiting on @aa-tolmachev and @nikicat)

___
*[chart/templates/deployment.yaml, line 43 at r1](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1#-MKoEOoLDC9EiYr1Hlmo:-MKoN1_A5OsltT4D4lZB:bl820hj) ([raw file](https://github.com/gosuai/gosu-deeppavlov-wot-qa/blob/09e121f7d84cb111e48376d9243bb76e8a7fd698/chart/templates/deployment.yaml#L43)):*
<details><summary><i>Previously, nikicat (Nikolay Bryskin) wrote…</i></summary><blockquote>

Между крешами контейнера файлы будут сохраняться, но если будет переезд на другую ноду - потеряются. А там код проверяет, что если модель уже есть, то второй раз не надо качать?
</blockquote></details>

Проверяет, второй раз модель не качается.

**Review by nikicat — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gosuai/gosu-deeppavlov-wot-qa/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aa-tolmachev)

**Pull request merged**
